### PR TITLE
Don't generate empty Abstract implementations

### LINKED ISSUE #18: Dce & abstracts
Seems like hxgenjs generates output for all abstracts even if their implementation is unused (even with `-dce full`).

image

### PR DESCRIPTION
**Pull request by benmerckx**
Fixes #18

### CODE REVIEW

**Comment by kevinresol** [comment]
Do we also need to check `cls.statics`?

**Comment by benmerckx** [comment]
Yes we do :) Let me try and add a test here.

**Comment by benmerckx** [comment]
It's actually only statics that need to be checked, as there's never an instance created. My first try was a bit too fast.

**Comment by kevinresol** [comment]
Looks very nice. Thanks!

**Pull request merged**
