### PR TITLE
Initial TypeScript definition and Haxe extern generation

### PR DESCRIPTION
**Pull request by jgranick**
I am using hxgenjs to output content from OpenFL, but I want to be able to use the content again from either TypeScript, or from Haxe. It may sound odd to use Haxe-generated code from Haxe again, but I think there are some interesting workflows this can enable.

Both are enabled using `-Dtsextern` or `-Dhxextern`, respectively, and are both rough. They are quality enough that I can compile code, but not to fully preserve all the correct types. I see this as a step forward in this direction. The initial results are enabling OpenFL on NPM: https://www.npmjs.com/package/openfl

### CODE REVIEW

**Comment by kevinresol** [comment]
Thanks for efforts!

Could you include a documentation or example on how to use the generated externs? 
The major reason is that I wish refactor this library to allow plugging in generators instead of hardcoding (with flags) like now. And I need a sample or, at best, tests to ensure I don't break things.

**Comment by jgranick** [comment]
Yeah! I had a feeling things could be done much more nicely, and certainly there are ways to improve the output to have the correct types.

Under https://www.npmjs.com/package/openfl, I have included a few samples for ES5, ES6, TypeScript and Haxe. First we run `-lib hxgenjs` over the usual OpenFL Haxe library, to generate ES5 modules in JavaScript, and (with these additions) also generate \*.d.ts/\*.hx definition/extern files.

This allows us to point to the same path in order to use TypeScript and Haxe on the generated ES5 code.

Like this one:

https://github.com/openfl/openfl-js/tree/master/samples/haxe/helloworld

I noticed today that I was having some errors compiling because "List.hx" and "haxe/io/Error.hx" were being generated. I didn't have them yesterday... I'm not sure if these are being properly omitted in my extern build script or not.

Last thought, I'm not sure if the externs should be generated at the same time as the ES5 modules, or not. I figured that they should probably be done at the same time (when enabled) because a lot of the same code processing could be re-used, making it much faster than running multiple times, but I could be wrong?

**Comment by back2dos** [comment]
@jgranick The compiler already has `--gen-hx-classes` for generating externs for you whole build. Granted, it generates externs for *everything*, but then again deleting a few files after building (in `Context.onAfterGenerate` for example) seems easy enough.

As for .d.ts definitions, have you considered [hxtsdgen](https://github.com/nadako/hxtsdgen)?

That said, I think it might be interesting to have an actual TS output (meaning the ES6 output would be just that stripped of types).

**Comment by elsassph** [comment]
I'd argue that generating d.ts files is totally the job of a JS output like hxgenjs (and in the future something native to the compiler).
Generating TS code is a bad idea, imho.

**Comment by jgranick** [comment]
@back2dos I had wondered if the compiler could generate the externs, though I wonder if there are few problems that might create. I am adding `@:jsRequire` to each class to automatically generate the needed imports, and had a TODO in mind to convert `@:enum abstract` to working enum classes (usable with `require("my/Enum")` and not `require("my/_Enum/Enum_Impl_")` but perhaps the built-in extern generation would help solve some of those problems)

I did consider hxstdgen, but the best is to generate TypeScript definitions matching the same module structure, and if we're going to process the whole class tree, perhaps we can save CPU time and output both JS modules and TS definitions at once?

I agree with Philippe that JS modules + TS/HX definitions is more useful

**Comment by elsassph** [comment]
Yes, `hxgenjs` is the one emitting the JS - it has better knowledge of the JS structure. 
`hxtsdgen` is expecting the single JS file output, where exports have to be specified explictly.

**Comment by jgranick** [comment]
Closed in favor of https://github.com/kevinresol/hxgenjs/pull/12

**Pull request closed without merging**
